#!/bin/bash
# Generate the practice cluster's credentials and write them as Secret manifests to
# cluster/bootstrap/secrets/generated.yaml (gitignored). Everything that needs a password or a
# key reads one of these Secrets; nothing is typed into git.
#   ./secrets.sh            write the file if missing, append any Secret added since
#   ./secrets.sh rotate     write new values (restart the pods that use them afterwards)
# Needs openssl and cast (Foundry) for the chain keys.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
OUT=$HERE/secrets/generated.yaml
export PATH="$HOME/.foundry/bin:$PATH"
command -v cast >/dev/null || { echo "cast (Foundry) is needed to derive the chain keys" >&2; exit 1; }
rand() { openssl rand -hex "$1"; }
# Test mnemonic of the upstream test-suite, read from the fhevm checkout so that no phrase or
# key is written into this repo. Every chain key below derives from it.
ROOT=$(cd "$HERE/../.." && pwd)
FHEVM_DIR=${FHEVM_DIR:-$ROOT/../zama-ai-repos/fhevm}
MNEMONIC=$(grep '^MNEMONIC=' "$FHEVM_DIR/test-suite/fhevm/templates/env/.env.host-node" | cut -d= -f2-)
[ -n "$MNEMONIC" ] || { echo "could not read MNEMONIC from $FHEVM_DIR/test-suite/fhevm/templates/env/.env.host-node" >&2; exit 1; }
key() { cast wallet private-key --mnemonic "$MNEMONIC" --mnemonic-index "$1"; }
mkdir -p "$HERE/secrets"; umask 077
if [ "${1:-}" = rotate ] || [ ! -f "$OUT" ]; then
  PG_PASS=$(rand 16); MINIO_ROOT_PASS=$(rand 16); S3_KEY=fhevm-$(rand 6); S3_SECRET=$(rand 20); GRAFANA_PASS=$(rand 8)
  cat > "$OUT" <<YAML
# Generated by secrets.sh, applied by make bootstrap. Not in git.
apiVersion: v1
kind: Namespace
metadata: { name: infra }
---
apiVersion: v1
kind: Namespace
metadata: { name: coproc }
---
apiVersion: v1
kind: Namespace
metadata: { name: monitoring }
---
# postgres itself
apiVersion: v1
kind: Secret
metadata: { name: postgres-credentials, namespace: infra }
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: $PG_PASS
  POSTGRES_DB: coprocessor
---
# minio root account plus the access key the workers use
apiVersion: v1
kind: Secret
metadata: { name: minio-credentials, namespace: infra }
type: Opaque
stringData:
  MINIO_ROOT_USER: minio-root
  MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASS
  ACCESS_KEY: $S3_KEY
  SECRET_KEY: $S3_SECRET
---
# what the coprocessor chart values reference (same names secrets-bootstrap.sh creates on testnet)
apiVersion: v1
kind: Secret
metadata: { name: coprocessor-db, namespace: coproc }
type: Opaque
stringData:
  username: postgres
  password: $PG_PASS
---
apiVersion: v1
kind: Secret
metadata: { name: coprocessor-s3, namespace: coproc }
type: Opaque
stringData:
  access_key: $S3_KEY
  secret_key: $S3_SECRET
---
# sql-exporter DSN (name and key from the exporter chart's values)
apiVersion: v1
kind: Secret
metadata: { name: sql-exporter-config, namespace: monitoring }
type: Opaque
stringData:
  DATA_SOURCE_NAME: postgres://postgres:$PG_PASS@postgres.infra.svc.cluster.local:5432/coprocessor?sslmode=disable
---
# Grafana admin login (the UI is anonymous read-only; admin is for editing dashboards)
apiVersion: v1
kind: Secret
metadata: { name: grafana-admin, namespace: monitoring }
type: Opaque
stringData:
  admin-user: admin
  admin-password: $GRAFANA_PASS
YAML
  echo "wrote $OUT"
fi
# Secrets added later are appended when missing, so an existing file keeps its passwords.
ensure() {  # ensure <name> <namespace> <heredoc on stdin>
  if grep -q "name: $1, namespace: $2" "$OUT"; then return; fi
  { echo "---"; cat; } >> "$OUT"; echo "added $2/$1"
}
ensure anvil-mnemonic infra <<YAML
# anvil funds 120 accounts from this phrase
apiVersion: v1
kind: Secret
metadata: { name: anvil-mnemonic, namespace: infra }
type: Opaque
stringData:
  MNEMONIC: "$MNEMONIC"
YAML
ensure host-chain-deployer coproc <<YAML
# host contracts deploy Job: the deployer is account 9 of the phrase, as in the upstream e2e env
apiVersion: v1
kind: Secret
metadata: { name: host-chain-deployer, namespace: coproc }
type: Opaque
stringData:
  mnemonic: "$MNEMONIC"
  deployer-private-key: $(key 9)
YAML
ensure coprocessor-tx-sender coproc <<YAML
# sns-worker attestation signer (later also tx-sender): account 11 of the phrase, the address
# registered as COPROCESSOR_SIGNER_ADDRESS_0 in coprocessor/host-contracts/values.yaml
apiVersion: v1
kind: Secret
metadata: { name: coprocessor-tx-sender, namespace: coproc }
type: Opaque
stringData:
  private-key: $(key 11)
YAML
ensure demo-sender coproc <<YAML
# coprocessor-demo Job: the account that deploys Add.sol and sends add(3,5), account 0 of the phrase
apiVersion: v1
kind: Secret
metadata: { name: demo-sender, namespace: coproc }
type: Opaque
stringData:
  private-key: $(key 0)
YAML
echo "$OUT is up to date"
