#!/bin/bash
# Generate the practice cluster's credentials once and write them as Secret manifests to
# cluster/bootstrap/secrets/generated.yaml (gitignored). Re-running keeps the existing file.
# Everything that needs a password reads one of these Secrets; nothing is typed into git.
#   ./secrets.sh            write the file if missing
#   ./secrets.sh rotate     write new values (restart the pods that use them afterwards)
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
OUT=$HERE/secrets/generated.yaml
if [ -f "$OUT" ] && [ "${1:-}" != rotate ]; then echo "$OUT exists, keeping it"; exit 0; fi
rand() { openssl rand -hex "$1"; }
PG_PASS=$(rand 16)
MINIO_ROOT_PASS=$(rand 16)
S3_KEY=fhevm-$(rand 6)
S3_SECRET=$(rand 20)
GRAFANA_PASS=$(rand 8)
mkdir -p "$HERE/secrets"
umask 077
cat > "$OUT" <<YAML
# Generated by secrets.sh, applied by make bootstrap. Not in git.
apiVersion: v1
kind: Namespace
metadata: { name: infra }
---
apiVersion: v1
kind: Namespace
metadata: { name: coproc }
---
apiVersion: v1
kind: Namespace
metadata: { name: monitoring }
---
# postgres itself
apiVersion: v1
kind: Secret
metadata: { name: postgres-credentials, namespace: infra }
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: $PG_PASS
  POSTGRES_DB: coprocessor
---
# minio root account plus the access key the workers use
apiVersion: v1
kind: Secret
metadata: { name: minio-credentials, namespace: infra }
type: Opaque
stringData:
  MINIO_ROOT_USER: minio-root
  MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASS
  ACCESS_KEY: $S3_KEY
  SECRET_KEY: $S3_SECRET
---
# what the coprocessor chart values reference (same names secrets-bootstrap.sh creates on testnet)
apiVersion: v1
kind: Secret
metadata: { name: coprocessor-db, namespace: coproc }
type: Opaque
stringData:
  username: postgres
  password: $PG_PASS
---
apiVersion: v1
kind: Secret
metadata: { name: coprocessor-s3, namespace: coproc }
type: Opaque
stringData:
  access_key: $S3_KEY
  secret_key: $S3_SECRET
---
# sql-exporter DSN (name and key from the exporter chart's values)
apiVersion: v1
kind: Secret
metadata: { name: sql-exporter-config, namespace: monitoring }
type: Opaque
stringData:
  DATA_SOURCE_NAME: postgres://postgres:$PG_PASS@postgres.infra.svc.cluster.local:5432/coprocessor?sslmode=disable
---
# Grafana admin login (the UI is anonymous read-only; admin is for editing dashboards)
apiVersion: v1
kind: Secret
metadata: { name: grafana-admin, namespace: monitoring }
type: Opaque
stringData:
  admin-user: admin
  admin-password: $GRAFANA_PASS
YAML
echo "wrote $OUT"
